spring:
  application:
    name: spring

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html