spring:
  application:
    name: spring

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db_mini_dump_lesson4/db.changelog-master.xml